baseURL: 'https://ercanakyuerek.de'
languageCode: en-us
theme: hello-friend-ng
pagination:
  pagerSize: 10
enableEmoji: true
services:
  googleAnalytics:
    id: G-WCX2MRFT7Z
params:
  homeSubtitle: Discover my world of creative web development, roller coaster simulations, and 3D graphics.
  disableReadOtherPosts: false
  enableSharingButtons: true
  keywords: 'homepage, blog'
  social:
    - name: "email"
      url: "mailto:ercan.akyuerek@gmail.com"
    - name: "xing"
      url: "https://www.xing.com/profile/Ercan_Akyuerek"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ercan-aky%C3%BCrek-732359183/"
    - name: "github"
      url: "https://github.com/geforcefan"
taxonomies:
  category: blog
  tag: tags
  series: series
languages:
  en:
    title: Ercan Aky√ºrek
    params:
      logo:
        logoText: ercanakyuerek.de
menu:
  main:
    - identifier: aboutme
      name: About me
      url: /about
    - identifier: blog
      name: Blog
      url: /posts
markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
            - - '\['
              - '\]'
            - - $$
              - $$
          inline:
            - - '\('
              - '\)'
        enable: true